faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 5
  similarity_threshold: 0.7

llm:
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0.0
    max_tokens: 2048

  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048